### ISSUE TITLE
Can't build on 6.6 kernel

### ISSUE THREAD

**Issue by denis7092** [linuxbuh/vhci_hcd#4]
vhci_hcd перестал собираться на ядре 6.2 и выше

DKMS make.log for vhci_hcd-1.15.1 for kernel 6.6.8-1 (x86_64)
Wed Dec 27 19:46:03 MSK 2023
make testconfig
make[1]: Entering directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
rm -f test/*.o test/*.ko test/.*.cmd test/.*.flags test/*.mod.c test/Module.symvers test/Module.markers test/modules.order
rm -rf test/.tmp_versions/
make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 EXTRA_CFLAGS='-Wno-unused -DEXPORT_SYMTAB -DKBUILD_EXTMOD -DINCLUDE_CORE_HCD=\"/lib/modules/6.6.8-1/build/include/linux/usb/hcd.h\" -DKERNEL_VER=6 ' modules
make[2]: Entering directory '/usr/lib/modules/6.6.8-1/build'
  CC [M]  /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test/test.o
  MODPOST /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test/Module.symvers
  CC [M]  /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test/test.mod.o
  LD [M]  /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test/test.ko
  BTF [M] /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test/test.ko
make[2]: Leaving directory '/usr/lib/modules/6.6.8-1/build'
mkdir -p conf/
echo "// do not edit; automatically generated by 'make testconfig' in vhci-hcd sourcedir" >conf/usb-vhci.config.h
echo "#define USB_VHCI_HCD_VERSION \"1.15.1\"" >>conf/usb-vhci.config.h
echo "#define USB_VHCI_HCD_DATE \"2023-12-27\"" >>conf/usb-vhci.config.h
echo "#define USB_VHCI_IOCIFC_VERSION \"1.15.1\"" >>conf/usb-vhci.config.h
echo "#define USB_VHCI_IOCIFC_DATE USB_VHCI_HCD_DATE" >>conf/usb-vhci.config.h
make clean-test
make[2]: Entering directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
rm -f test/*.o test/*.ko test/.*.cmd test/.*.flags test/*.mod.c test/Module.symvers test/Module.markers test/modules.order
rm -rf test/.tmp_versions/
make[2]: Leaving directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
if make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 EXTRA_CFLAGS='-Wno-unused -DEXPORT_SYMTAB -DKBUILD_EXTMOD -DINCLUDE_CORE_HCD=\"/lib/modules/6.6.8-1/build/include/linux/usb/hcd.h\" -DKERNEL_VER=6 -DTEST_GIVEBACK_MECH' modules >/dev/null 2>&1; then \
	echo "//#define OLD_GIVEBACK_MECH" >>conf/usb-vhci.config.h; \
else \
	echo "#define OLD_GIVEBACK_MECH" >>conf/usb-vhci.config.h; \
fi
make clean-test
make[2]: Entering directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
rm -f test/*.o test/*.ko test/.*.cmd test/.*.flags test/*.mod.c test/Module.symvers test/Module.markers test/modules.order
rm -rf test/.tmp_versions/
make[2]: Leaving directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
if make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 EXTRA_CFLAGS='-Wno-unused -DEXPORT_SYMTAB -DKBUILD_EXTMOD -DINCLUDE_CORE_HCD=\"/lib/modules/6.6.8-1/build/include/linux/usb/hcd.h\" -DKERNEL_VER=6 -DTEST_DEV_BUS_ID' modules >/dev/null 2>&1; then \
	echo "//#define OLD_DEV_BUS_ID" >>conf/usb-vhci.config.h; \
else \
	echo "#define OLD_DEV_BUS_ID" >>conf/usb-vhci.config.h; \
fi
make clean-test
make[2]: Entering directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
rm -f test/*.o test/*.ko test/.*.cmd test/.*.flags test/*.mod.c test/Module.symvers test/Module.markers test/modules.order
rm -rf test/.tmp_versions/
make[2]: Leaving directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
if make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 EXTRA_CFLAGS='-Wno-unused -DEXPORT_SYMTAB -DKBUILD_EXTMOD -DINCLUDE_CORE_HCD=\"/lib/modules/6.6.8-1/build/include/linux/usb/hcd.h\" -DKERNEL_VER=6 -DTEST_DEV_INIT_NAME' modules >/dev/null 2>&1; then \
	echo "//#define NO_DEV_INIT_NAME" >>conf/usb-vhci.config.h; \
else \
	echo "#define NO_DEV_INIT_NAME" >>conf/usb-vhci.config.h; \
fi
make clean-test
make[2]: Entering directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
rm -f test/*.o test/*.ko test/.*.cmd test/.*.flags test/*.mod.c test/Module.symvers test/Module.markers test/modules.order
rm -rf test/.tmp_versions/
make[2]: Leaving directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
if make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/test BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 EXTRA_CFLAGS='-Wno-unused -DEXPORT_SYMTAB -DKBUILD_EXTMOD -DINCLUDE_CORE_HCD=\"/lib/modules/6.6.8-1/build/include/linux/usb/hcd.h\" -DKERNEL_VER=6 -DTEST_HAS_TT_FLAG' modules >/dev/null 2>&1; then \
	echo "//#define NO_HAS_TT_FLAG" >>conf/usb-vhci.config.h; \
else \
	echo "#define NO_HAS_TT_FLAG" >>conf/usb-vhci.config.h; \
fi
echo "// end of file" >>conf/usb-vhci.config.h
make[1]: Leaving directory '/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build'
make -C /lib/modules/6.6.8-1/build M=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build PWD=/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build BUILD_PREFIX= KDIR=/lib/modules/6.6.8-1/build KVERSION=6.6.8-1 modules
make[1]: Entering directory '/usr/lib/modules/6.6.8-1/build'
  CC [M]  /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-hcd.o
  CC [M]  /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.o
/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.c:1073:10: error: ‘struct class’ has no member named ‘owner’
 1073 |         .owner = THIS_MODULE,
      |          ^~~~~
In file included from ./include/linux/linkage.h:7,
                 from ./arch/x86/include/asm/cache.h:5,
                 from ./include/linux/cache.h:6,
                 from ./arch/x86/include/asm/current.h:9,
                 from ./include/linux/sched.h:12,
                 from ./include/linux/uaccess.h:8,
                 from /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.c:23:
./include/linux/export.h:29:21: error: initialization of ‘const char *’ from incompatible pointer type ‘struct module *’ [-Werror=incompatible-pointer-types]
   29 | #define THIS_MODULE (&__this_module)
      |                     ^
/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.c:1073:18: note: in expansion of macro ‘THIS_MODULE’
 1073 |         .owner = THIS_MODULE,
      |                  ^~~~~~~~~~~
./include/linux/export.h:29:21: note: (near initialization for ‘vhci_iocifc_class.name’)
   29 | #define THIS_MODULE (&__this_module)
      |                     ^
/home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.c:1073:18: note: in expansion of macro ‘THIS_MODULE’
 1073 |         .owner = THIS_MODULE,
      |                  ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build/usb-vhci-iocifc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.6.8-1/build/Makefile:1911: /home/arch/abs/testing/vhci_hcd/src/build/vhci_hcd/1.15.1/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.8-1/build'
make: *** [Makefile:82: default] Error 2

**Comment by denis7092** [comment]
Решение - патч:
`--- a/usb-vhci-iocifc.c.orig	2021-05-13 13:51:41.000000000 +0300
+++ b/usb-vhci-iocifc.c	2024-01-04 19:26:13.240059603 +0300
@@ -207,7 +207,7 @@
 	file->private_data = vdev;
 
 	// copy id to user space
-	__put_user(usb_vhci_dev_id(vdev), &arg->id);
+	put_user(usb_vhci_dev_id(vdev), &arg->id);
 
 	// copy bus-id to user space
 	dname = usb_vhci_dev_name(vdev);
@@ -216,15 +216,15 @@
 	if(copy_to_user(arg->bus_id, dname, i))
 	{
 		vhci_printk(KERN_WARNING, "Failed to copy bus_id to userspace.\n");
-//		__put_user('\0', arg->bus_id);
-		__put_user('\0', arg->bus_id + 0);
+//		put_user('\0', arg->bus_id);
+		put_user('\0', arg->bus_id + 0);
 	}
 	// make sure the last character is null
-	__put_user('\0', arg->bus_id + i);
+	put_user('\0', arg->bus_id + i);
 
 	usbbusnum = usb_vhci_dev_busnum(vdev);
 	vhci_printk(KERN_INFO, "Usb bus #%d\n", usbbusnum);
-	__put_user(usbbusnum, &arg->usb_busnum);
+	put_user(usbbusnum, &arg->usb_busnum);
 
 	return 0;
 }
@@ -1070,7 +1070,7 @@
 static int vhci_iocifc_major;
 
 static struct class vhci_iocifc_class = {
-	.owner = THIS_MODULE,
+//*	.owner = THIS_MODULE, *//
 	.name = driver_name
 };
 
`

**Comment by denis7092** [comment]
Вот решение - патч:

```c
--- a/usb-vhci-iocifc.c.orig	2021-05-13 13:51:41.000000000 +0300
+++ b/usb-vhci-iocifc.c	2024-01-04 19:26:13.240059603 +0300
@@ -207,7 +207,7 @@
 	file->private_data = vdev;
 
 	// copy id to user space
-	__put_user(usb_vhci_dev_id(vdev), &arg->id);
+	put_user(usb_vhci_dev_id(vdev), &arg->id);
 
 	// copy bus-id to user space
 	dname = usb_vhci_dev_name(vdev);
@@ -216,15 +216,15 @@
 	if(copy_to_user(arg->bus_id, dname, i))
 	{
 		vhci_printk(KERN_WARNING, "Failed to copy bus_id to userspace.\n");
-//		__put_user('\0', arg->bus_id);
-		__put_user('\0', arg->bus_id + 0);
+//		put_user('\0', arg->bus_id);
+		put_user('\0', arg->bus_id + 0);
 	}
 	// make sure the last character is null
-	__put_user('\0', arg->bus_id + i);
+	put_user('\0', arg->bus_id + i);
 
 	usbbusnum = usb_vhci_dev_busnum(vdev);
 	vhci_printk(KERN_INFO, "Usb bus #%d\n", usbbusnum);
-	__put_user(usbbusnum, &arg->usb_busnum);
+	put_user(usbbusnum, &arg->usb_busnum);
 
 	return 0;
 }
@@ -1070,7 +1070,7 @@
 static int vhci_iocifc_major;
 
 static struct class vhci_iocifc_class = {
-	.owner = THIS_MODULE,
+//*	.owner = THIS_MODULE, *//
 	.name = driver_name
 };
```

**Comment by Markiz-de-Karabas** [comment]
На Ядре 6.12 опять ошибка...

`/usr/src/6/vhci_hcd-1.15.1/usb-vhci-hcd.c:1027:23: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
 1027 |         .remove     = vhci_hcd_remove,
      |                       ^~~~~~~~~~~~~~~
/usr/src/6/vhci_hcd-1.15.1/usb-vhci-hcd.c:1027:23: note: (near initialization for ‘vhci_hcd_driver.<anonymous>.remove’)
make[3]: *** [/usr/src/linux-headers-6.12.85+deb13-common/scripts/Makefile.build:234: /usr/src/6/vhci_hcd-1.15.1/usb-vhci-hcd.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.12.85+deb13-common/Makefile:1980: /usr/src/6/vhci_hcd-1.15.1] Error 2
make[1]: *** [/usr/src/linux-headers-6.12.85+deb13-common/Makefile:236: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.85+deb13-amd64'
make: *** [Makefile:35: default] Error 2`
